// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHaLvye5UA5I9m-CMDXoDfyFFdd90o17o',
    appId: '1:196945139975:web:3500b11c8cb03dcc8c4da2',
    messagingSenderId: '196945139975',
    projectId: 'tastemix-2k24',
    authDomain: 'tastemix-2k24.firebaseapp.com',
    storageBucket: 'tastemix-2k24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHwLAD12CRjChq-lytRVBNQ-n5zJFKVE',
    appId: '1:196945139975:android:20dc521b3ff8d8388c4da2',
    messagingSenderId: '196945139975',
    projectId: 'tastemix-2k24',
    storageBucket: 'tastemix-2k24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiCF91FbnqwMlvxPhoknozqQV2TeziWDE',
    appId: '1:196945139975:ios:c836b5fb551141248c4da2',
    messagingSenderId: '196945139975',
    projectId: 'tastemix-2k24',
    storageBucket: 'tastemix-2k24.appspot.com',
    iosBundleId: 'com.example.tastemix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiCF91FbnqwMlvxPhoknozqQV2TeziWDE',
    appId: '1:196945139975:ios:b52e9bbb62792e4d8c4da2',
    messagingSenderId: '196945139975',
    projectId: 'tastemix-2k24',
    storageBucket: 'tastemix-2k24.appspot.com',
    iosBundleId: 'com.example.tastemix.RunnerTests',
  );
}
